<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- References -->
	<ItemGroup>
		<!-- Include all DLLs in lib/ -->
		<Reference Include="lib/*.dll" />
	</ItemGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Common\SomethingYouShouldKnowAboutSomeRecipes.txt" />
	  <AdditionalFiles Remove="Content\Items\SomethingYouShouldKnowAboutSomeRecipes.txt" />
	  <AdditionalFiles Remove="SomethingYouShouldKnowAboutSomeRecipes.txt" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\NPCs\SnowMobs\" />
	  <Folder Include="Content\Projectiles\Prefixes\FishingPrefixes\" />
	</ItemGroup>

</Project>