<Project Sdk="Microsoft.NET.Sdk">

<!-- some stuff to make vscode happy to compile on linux	-->
	<PropertyGroup>
		<TargetFramework Condition="'$(TargetFramework)' == ''">net8.0</TargetFramework>
	</PropertyGroup>

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- References -->
	<ItemGroup>
		<!-- Include all DLLs in lib/ -->
		<Reference Include="lib/*.dll" />
	</ItemGroup>

</Project>