<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Content\Tiles\Lighting\**" />
	  <Compile Remove="Content\Tiles\Lighting\**" />
	  <EmbeddedResource Remove="Content\Tiles\Lighting\**" />
	  <None Remove="Content\Tiles\Lighting\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Content\Items\Weapons\Melee\Scarlet.png" />
	  <None Remove="Content\Items\Weapons\Melee\XenonWaraxe.png" />
	  <None Remove="Content\NPCs\Bandit.png" />
	  <None Remove="Content\NPCs\BanditLooter.PNG" />
	  <None Remove="Content\NPCs\BloodBolt.png" />
	  <None Remove="Content\NPCs\CrimsonCultist.png" />
	  <None Remove="Content\Items\Components\CursedBoneDust.png" />
	  <None Remove="Content\Items\Components\RefinedBoneDust.png" />
	  <None Remove="Content\Items\Pouch.png" />
	  <None Remove="Content\Items\RhyoliteBlock.png" />
	  <None Remove="Content\Items\RhyoliteWall.png" />
	  <None Remove="Content\Items\Valuables\GemPouch.png" />
	  <None Remove="Content\Items\Valuables\MusicalAlbum.png" />
	  <None Remove="Content\Items\Valuables\Perfume.png" />
	  <None Remove="Content\Items\Valuables\RareBook.png" />
	  <None Remove="Content\Items\Valuables\UnstablePowder.png" />
	  <None Remove="Content\Items\WoolBlock.png" />
	  <None Remove="Content\NPC_110.png" />
	  <None Remove="Content\Tiles\image.png" />
	  <None Remove="Content\Tiles\WoolBlock.png" />
	  <None Remove="Content\Walls\RhyoliteWallUnsafe.png" />
	  <None Remove="icon.png" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Content\Items\Placeable\Furniture\Rhyolite\" />
	  <Folder Include="Content\Items\Placeable\Wall\" />
	  <Folder Include="Content\NPCs\Template\" />
	  <Folder Include="Content\Tiles\Furniture\Rhyolite\" />
	</ItemGroup>

	<!-- References -->

</Project>